### ISSUE TITLE
Hey! Nice repo

### ISSUE THREAD

**Issue by alvesvin** [NWylynko/trpc-monorepo-microservices#1]
I was looking for tRPC and microsservices and immediatly found your repo. Very nicely structured, but what about the deploy? Does the tRPC services inside the "services" folder can be deployed to distinct server instances?

**Comment by alvesvin** [comment]
Actually I don't think it would be a problem because every server could have a copy of the entire codebase. The only thing we would need to care about is the URLs the clients are connecting to.

**Comment by NWylynko** [comment]
Hey @alvesvin, great to see this repo can be of any help, as you can see from the commits I haven't touched this in a while. Deploying this monorepo is more of a turborepo concern, and I believe turbo has a prune feature that can split out the monorepo in to seperate folders to be deployed with only the relevant dependencies. I could be thinking of something else and be wrong about it. Also the urls to point to the different services should be relatively simple, just pass them in as environment variables.
